version: '3.8'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile.api
    container_name: api
    restart: always
    ports:
      - 8000:8000
    environment:
      - MONGO_URI=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
      - CASSANDRA_CONTACT_POINTS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=airportflightmanagement
      - NEO4J_URIS=bolt://neo4j1:7687,bolt://neo4j2:7687,bolt://neo4j3:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - NUM_RECORDS=2000000
    networks:
      - app-network

networks:
  app-network:
    external: true

