services:
  cassandra1:
    image: cassandra:5.0
    container_name: cassandra1
    restart: always
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra1_data:/var/lib/cassandra
    networks:
      - cassandra-network
    
  cassandra2:
    image: cassandra:5.0
    container_name: cassandra2
    restart: always
    ports:
      - 9043:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra1
    depends_on:
      - cassandra1
    volumes:
      - cassandra2_data:/var/lib/cassandra
    networks:
      - cassandra-network
    
  cassandra3:
    image: cassandra:5.0
    container_name: cassandra3
    restart: always
    ports:
      - 9044:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra1
    depends_on:
      - cassandra1
    volumes:
      - cassandra3_data:/var/lib/cassandra
    networks:
      - cassandra-network

  populate_cassandra:
    build:
      context: .
      dockerfile: Dockerfile.populate_cassandra
    depends_on:
      - cassandra1
      - cassandra2
      - cassandra3
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=airportflightmanagement
    networks:
      - cassandra-network

volumes:
  cassandra1_data:
  cassandra2_data:
  cassandra3_data:

networks:
  cassandra-network:
    driver: bridge
