services:
  neo4j1:
    image: neo4j:5.23.0-enterprise
    container_name: neo4j1
    restart: always
    ports:
      - 7687:7687
      - 7474:7474
      - 7473:7473
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_dbms_cluster_discovery_endpoints=neo4j1:5000,neo4j2:5000,neo4j3:5000
      - NEO4J_server_discovery_advertised__address=neo4j1:5000
      - NEO4J_server_cluster_advertised__address=neo4j1:6000
      - NEO4J_server_cluster_raft_advertised__address=neo4j1:7000
      - NEO4J_server_bolt_advertised__address=neo4j1:7687
      - NEO4J_server_http_advertised__address=neo4j1:7474
      - NEO4J_server_https_advertised__address=neo4j1:7473
    volumes:
      - neo4j1_data:/data
      - neo4j1_logs:/logs
      - neo4j1_import:/var/lib/neo4j/import
      - neo4j1_plugins:/plugins
    networks:
      - app-network

  neo4j2:
    image: neo4j:5.23.0-enterprise
    container_name: neo4j2
    restart: always
    ports:
      - 7688:7687
      - 7475:7474
      - 7476:7473
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_dbms_cluster_discovery_endpoints=neo4j1:5000,neo4j2:5000,neo4j3:5000
      - NEO4J_server_discovery_advertised__address=neo4j2:5000
      - NEO4J_server_cluster_advertised__address=neo4j2:6000
      - NEO4J_server_cluster_raft_advertised__address=neo4j2:7000
      - NEO4J_server_bolt_advertised__address=neo4j2:7687
      - NEO4J_server_http_advertised__address=neo4j2:7474
      - NEO4J_server_https_advertised__address=neo4j2:7473
    volumes:
      - neo4j2_data:/data
      - neo4j2_logs:/logs
      - neo4j2_import:/var/lib/neo4j/import
      - neo4j2_plugins:/plugins
    networks:
      - app-network

  neo4j3:
    image: neo4j:5.23.0-enterprise
    container_name: neo4j3
    restart: always
    ports:
      - 7689:7687
      - 7477:7474
      - 7478:7473
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_dbms_cluster_discovery_endpoints=neo4j1:5000,neo4j2:5000,neo4j3:5000
      - NEO4J_server_discovery_advertised__address=neo4j3:5000
      - NEO4J_server_cluster_advertised__address=neo4j3:6000
      - NEO4J_server_cluster_raft_advertised__address=neo4j3:7000
      - NEO4J_server_bolt_advertised__address=neo4j3:7687
      - NEO4J_server_http_advertised__address=neo4j3:7474
      - NEO4J_server_https_advertised__address=neo4j3:7473
    volumes:
      - neo4j3_data:/data
      - neo4j3_logs:/logs
      - neo4j3_import:/var/lib/neo4j/import
      - neo4j3_plugins:/plugins
    networks:
      - app-network

  populate_neo4j:
    build:
      context: .
      dockerfile: Dockerfile.populate_neo4j
    depends_on:
      - neo4j1
      - neo4j2
      - neo4j3
    environment:
      - NEO4J_URI=bolt://neo4j1:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - NUM_RECORDS=2000000
    networks:
      - app-network


volumes:
  neo4j1_data:
  neo4j1_logs:
  neo4j1_import:
  neo4j1_plugins:
  neo4j2_data:
  neo4j2_logs:
  neo4j2_import:
  neo4j2_plugins:
  neo4j3_data:
  neo4j3_logs:
  neo4j3_import:
  neo4j3_plugins:

networks:
  app-network:
    external: true

